### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [HugoMVale/HR-WENO#1]
I suggest adding topics such as `weno`, `partial-differential-equations`, `pde` in the About section at https://github.com/HugoMVale/HR-WENO.

**Comment by HugoMVale** [comment]
Good idea. Thanks for the suggestion. I have been refactoring the code, adding tests, etc. Once I am done with the examples, I will update the readme file.

**Comment by HugoMVale** [comment]
@Beliavsky Done! Thanks again for the hint!
